import Head from 'next/head';
import { Inter } from 'next/font/google';
import {
  useUser,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton
} from "@clerk/nextjs";
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Visualise Event Feedbacks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col text-slate-100 justify-center'>
        <div className='p-4 m-2 border-2 border-white flex justify-between'>
          <h1 className='text-4xl font-bold'>Ebento</h1>
          <div className='flex flex-row mx-2 items-center'>
            <SignedIn>
              {/* Mount the UserButton component */}
              {
                user && <p className='text-lg mx-2'>{user.fullName}</p>
              }
              <UserButton />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
        </div>

        <div className='flex flex-col mt-12 justify-center items-center'>
          <h1 className='text-4xl font-bold'>Visualise Event Feedbacks</h1>
          <p className='text-xl'>Get feedbacks from your event attendees and track satisfaction metrics</p>
        </div>
      </main>
    </>
  )
}
